services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      # Синхронизация папки, чтобы изменения кода работали без перезагрузки
      - .:/app
      # Исключаем node_modules контейнера из синхронизации
      - /app/node_modules
